version: '3'
services:
  app:
    image: decidim/decidim:0.23.4
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    environment:
      - PORT=3000
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379
    ports:
      - 3000:3000
    links:
      - pg
      - redis
    command: bundle exec puma
  pg:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  redis:
    image: redis
    volumes:
      - redis-data:/data
volumes:
  node_modules: {}
  bundle: {}
  pg-data: {}
  redis-data: {}
